### ISSUE TITLE
启动服务后如何在浏览器中浏览界面

### ISSUE THREAD

**Issue by xuchaoxi** [dnc1994/ABS#1]
你好，请问一下再执行完`python server.py`后，如何在浏览器中浏览相应的界面？

**Comment by shuding** [comment]
你需要安装 NodeJS，然后在本项目目录下运行：

```bash
npm i gulp -g
gulp webserver
```

保持 `python server.py` 也开启，打开 [http://localhost:8888](http://localhost:8888)，应该可以看到界面。

**Comment by xuchaoxi** [comment]
噢噢，现在可以了，thx。
